# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59c0d00e177039b1422fa0877b80c197840290ffc9ecf462362ea408827bbfd5f48a2993425f9c0ffc3426b7efe2ae2f657db5d8c4cc6277ae471784d2aaf84

test:
  secret_key_base: ac0832f729475e1fb2e9ab71a785e9ae3583045b08128ea871950e7b10e4e947392e49ee4fb1b3c10759e2b23bd10fa4d6cfe1b396a022364f94aeee90eb2fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
